import { PLAN, MUSCLES, getVolZone } from './training-data'

function todayStr() {
  return new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
}

function formatEntry(entry) {
  const time = new Date(entry.created_at).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })
  const src = entry.source !== 'manual' ? ` (${entry.source})` : ''
  return `${time}  ${entry.name}${src}\n  ${entry.calories} cal | ${entry.protein}g P | ${entry.fiber}g fiber | ${entry.carbs}g carbs`
}

function formatSetLog(exerciseName, sets) {
  if (!sets || sets.length === 0) return `  ${exerciseName}: not logged`
  const setStrs = sets.map((s, i) =>
    `set ${i + 1}: ${s.weight || '—'}lbs × ${s.reps || '—'} reps (RIR ${s.rir ?? '?'})`
  )
  return `  ${exerciseName}:\n    ${setStrs.join(' | ')}`
}

export function buildExport({ trainingState, nutritionEntries, nutritionTotals, weightHistory, weeklyHistory }) {
  const lines = []
  const now = new Date()

  lines.push(`# GymShred Export — ${todayStr()}`)
  lines.push('')

  // ── Training ──
  lines.push('## Training')

  const dayOfWeek = now.getDay() // 0=Sun
  const planMap = [6, 0, 1, 2, 3, 4, 5] // JS day → PLAN index
  const todayPlan = PLAN[planMap[dayOfWeek]]
  const { week, mesoLen, sess, vols, sessionLogs } = trainingState

  lines.push(`Week ${week} of ${mesoLen} · ${sess} sessions completed`)
  lines.push('')

  if (todayPlan && !todayPlan.rest) {
    lines.push(`**Today: ${todayPlan.label} — ${todayPlan.title} (${todayPlan.subtitle})**`)
    const todayKey = `${todayPlan.label.toLowerCase()}-w${week}`
    const todayLog = sessionLogs[todayKey] || {}
    todayPlan.exercises.forEach(ex => {
      const sets = todayLog[ex.name]
      lines.push(formatSetLog(ex.name, sets))
    })
    lines.push('')
  }

  lines.push('**Weekly Volume:**')
  MUSCLES.forEach(m => {
    const sets = vols[m.name] ?? m.mev
    const zone = getVolZone(m.name, sets)
    const zoneLabel = zone === 'mav' ? '✓ MAV' : zone === 'mrv' ? '⚠ MRV' : zone === 'below' ? '↓ Below MEV' : 'MEV'
    lines.push(`  ${m.name}: ${sets} sets/wk [${zoneLabel}] (MEV ${m.mev} / MAV ${m.mav[0]}-${m.mav[1]} / MRV ${m.mrv})`)
  })
  lines.push('')

  // ── Nutrition ──
  lines.push('## Nutrition — Today')

  if (nutritionTotals) {
    const { calories, protein, fiber, carbs } = nutritionTotals
    const calPct = Math.round((calories / 3300) * 100)
    const proPct = Math.round((protein / 200) * 100)
    lines.push(`Cal: ${calories} / 3,300 (${calPct}%) | Protein: ${protein}g / 200g (${proPct}%) | Fiber: ${fiber}g | Carbs: ${carbs}g`)
    lines.push('')
  }

  if (nutritionEntries && nutritionEntries.length > 0) {
    lines.push('**Food Log:**')
    nutritionEntries.forEach(e => lines.push(formatEntry(e)))
    lines.push('')
  } else {
    lines.push('No entries logged today.')
    lines.push('')
  }

  // ── 7-day averages ──
  if (weeklyHistory && weeklyHistory.length > 0) {
    const latest = weeklyHistory[0]
    lines.push('## 7-Day Averages')
    lines.push(`Avg calories: ${Math.round(latest.avg_calories || 0)}`)
    lines.push(`Avg protein: ${Math.round(latest.avg_protein || 0)}g`)
    lines.push(`Days protein goal hit (≥190g): ${latest.protein_hit_days || 0}/7`)
    lines.push(`Days calories in range (3,100–3,500): ${latest.calorie_range_days || 0}/7`)
    lines.push('')
  }

  // ── Weight ──
  if (weightHistory && weightHistory.length >= 2) {
    const latest = weightHistory[0]
    const oldest = weightHistory[weightHistory.length - 1]
    const trend = (latest.weight_lbs - oldest.weight_lbs).toFixed(1)
    const trendStr = trend > 0 ? `+${trend}` : `${trend}`
    lines.push('## Weight')
    lines.push(`Latest: ${latest.weight_lbs} lbs (${latest.date})`)
    lines.push(`Trend over ${weightHistory.length} days: ${trendStr} lbs`)
    if (weightHistory.length >= 7) {
      const last7 = weightHistory.slice(0, 7)
      const avg7 = (last7.reduce((s, e) => s + e.weight_lbs, 0) / last7.length).toFixed(1)
      lines.push(`7-day rolling average: ${avg7} lbs`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('*Generated by GymShred — paste into Claude for analysis*')

  return lines.join('\n')
}

export function buildDayExport({ date, entries, totals }) {
  const lines = []

  const dateStr = new Date(date + 'T12:00:00').toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  })

  lines.push(`# Nutrition Log — ${dateStr}`)
  lines.push('')

  if (totals) {
    const { calories, protein, fiber, carbs } = totals
    lines.push(`Cal: ${calories} | Protein: ${protein}g | Fiber: ${fiber}g | Carbs: ${carbs}g`)
    lines.push('')
  }

  if (entries && entries.length > 0) {
    lines.push('**Food Log:**')
    entries.forEach(e => lines.push(formatEntry(e)))
  } else {
    lines.push('No entries logged.')
  }

  lines.push('')
  lines.push('---')
  lines.push('*Generated by GymShred — paste into Claude for analysis*')

  return lines.join('\n')
}
